### ISSUE TITLE
I was wondering if there was a way to extract objects from the scene individually, thank you very much

### ISSUE THREAD

**Issue by Foxbeated** [OpenRobotLab/GRUtopia#11]
I was wondering if there was a way to extract objects from the scene individually, thank you very much

**Comment by Boyu-Mi** [comment]
You can use [NVIDIA USD library](https://docs.omniverse.nvidia.com/kit/docs/pxr-usd-api/105.0.2/pxr/Usd.html)  to parse the scenes in USD format.

**Comment by APX103** [comment]
Hey, thank you for your interest. And I think , You can manually extract using this tool ([USD Composer](https://docs.omniverse.nvidia.com/composer/latest/index.html)). Or use python script to implement it through [this library](https://docs.omniverse.nvidia.com/kit/docs/pxr-usd-api/105.0.2/pxr/Usd.html)
