### ISSUE TITLE
Does GRUtopia support multi-agent interaction?

### ISSUE THREAD

**Issue by zchoi** [OpenRobotLab/GRUtopia#12]
Great work！I'm inquisitive if the GRUtopia supports multi-agent interactions?

**Comment by HanqingWangAI** [comment]
Hi @zchoi,

Thank you for your interest in our project!

We currently offer a framework for customizing a multi-agent scenario, which you can refer to in the example provided at https://github.com/OpenRobotLab/GRUtopia/blob/main/demo/h1_npc.py. This example should serve as a helpful starting point for creating your own multi-agent interactions.

Please feel free to reach out if you have any questions or need further assistance.

**Comment by zchoi** [comment]
Got it. 👍
