### ISSUE TITLE
May I ask if you can provide a Windows version of the project installation? Thank you.

### ISSUE THREAD

**Issue by 1018weijia** [OpenRobotLab/GRUtopia#14]

**Comment by uzuku** [comment]
Technically if you have a ready Isaac Sim installation on Windows and a corresponding python environment, you can install the project by just

```shell
cd PATH/TO/ISAAC_SIM/ROOT
git clone git@github.com:OpenRobotLab/GRUtopia.git
cd GRUtopia
pip install -e .
```

For the python environment setup on Windows you can refer to https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html

**Comment by 1018weijia** [comment]
> Technically if you have a ready Isaac Sim installation on Windows and a corresponding python environment, you can install the project by just
> 
> ```shell
> cd PATH/TO/ISAAC_SIM/ROOT
> git clone git@github.com:OpenRobotLab/GRUtopia.git
> cd GRUtopia
> pip install -e .
> ```
> 
> For the python environment setup on Windows you can refer to https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html

Thank you for your answer. I have successfully deployed on Windows and run three of the demos. Only the last NPC demo has not been run yet. Additionally, the sh files used in the project also need to be converted to bat files to run on Windows

**Comment by 1018weijia** [comment]
The replication of Windows only requires converting the sh file into a bat file for execution. The other steps are the same as local Linux installation. The bat file can be found on the website:
https://www.notion.so/Windows-support-for-GRUtopia-ca3a286b7ab44c57b8538582ad6267a3?pvs=4
