### ISSUE TITLE
Other Robots

### ISSUE THREAD

**Issue by percypeng5221** [OpenRobotLab/GRUtopia#17]
Hi, I saw in your demo that there are a lot more robots including unitree and boston dynamics. But in this repo, there seems to be only robots of unitree h1? Do you plan to release the code for other robots?

**Comment by HanqingWangAI** [comment]
Hi @percypeng5221, we will release the control policy for unitree aliengo in the next few weeks. Moving forward, we will also be progressively rolling out control policies for other popular robots.

**Comment by quanting-xie** [comment]
Are the control policies for other robots released?
