### ISSUE TITLE
Omniverse Streaming Client

### ISSUE THREAD

**Issue by qZhang88** [OpenRobotLab/GRUtopia#5]
Is it possible to use Omniverse Streaming Client to connect sim in docker.

![image](https://github.com/user-attachments/assets/5352dafd-a80e-4a70-99da-c2e84908f780)

**Comment by APX103** [comment]
try this script `/isaac-sim/isaac-sim.headless.native.sh` with container's `--network host`

**Comment by APX103** [comment]
try this script `./isaac-sim.headless.native.sh --allow-root` at `/isaac-sim` in container. with container flag `--network host`.

**Comment by qZhang88** [comment]
> try this script `./isaac-sim.headless.native.sh --allow-root` at `/isaac-sim` in container. with container flag `--network host`.

directly run script is ok, but I want to connect to those demos.

**Comment by APX103** [comment]
Well. This feature is not supported yet. It well be supported soon.
I pushed a new demo you can try: [Here is the commit info](https://github.com/OpenRobotLab/GRUtopia/commit/39c043b606f5ed3cf1a82bffa7f17d07eeb08c35)

try run this in container:

``` sh
python ./GRUtopia/demo/h1_locomotion_native.py
```

**Comment by APX103** [comment]
Hello, I closed this issue. We can reopen it if necessary.
